version: '3'
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/www/webapp
      - ./data/init-db:/docker-entrypoint-initdb.d
      - ./data/data-db:/lib/mysql
    restart: always
    env_file:
      - ./env/conf.env
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - webapp:/webapp
      - ./nginx/log:/var/log/nginx
    depends_on:
      - uwsgi
    env_file:
      - ./env/conf.env
  uwsgi:
    build: .
    restart: always
    # command: sh -c "./wait-for-it.sh db:3306; uwsgi  --emperor /etc/uwsgi/uwsgi.ini"
    command: sh -c "./wait-for-it.sh db:3306; uwsgi --ini /etc/uwsgi/uwsgi.ini"
    ports:
     - "8888:8000"
    volumes:
      - ./webapp:/var/www/webapp
    depends_on:
        - db
    env_file:
      - ./env/conf.env

volumes:
  webapp:
  data:
